/**
 * Codegen script: converts ACL4SSR rule files into TypeScript modules.
 *
 * Scans:
 *   - ../Clash/*.list          → rule arrays  → server/codegen/rules.ts
 *   - ../Clash/Ruleset/*.list  → rule arrays  → server/codegen/ruleset.ts
 *   - ../Clash/config/*.ini    → preset defs  → server/codegen/presets.ts
 *
 * Run: npx tsx scripts/codegen.ts
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const ACL4SSR_DIR = path.resolve(ROOT, '..')
const CLASH_DIR = path.join(ACL4SSR_DIR, 'Clash')
const RULESET_DIR = path.join(CLASH_DIR, 'Ruleset')
const CONFIG_DIR = path.join(CLASH_DIR, 'config')
const OUTPUT_DIR = path.join(ROOT, 'server', 'codegen')

// ──────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────

function readFileLines(filePath: string): string[] {
  if (!fs.existsSync(filePath)) return []
  const content = fs.readFileSync(filePath, 'utf-8').replace(/\r\n/g, '\n')
  return content
    .split('\n')
    .map(l => l.trim())
    .filter(l => l !== '' && !l.startsWith('#') && !l.startsWith(';'))
}

function toPascalCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9]/g, '_')
    .replace(/(_|^)([a-z])/g, (_, __, c) => c.toUpperCase())
    .replace(/^([0-9])/, '_$1')
}

function escapeForTemplate(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r/g, '')
    .replace(/\n/g, '\\n')
}

/** Generate a variable name for a rule file path relative to Clash/ */
function ruleVarName(relativePath: string, prefix: string): string {
  const key = relativePath.replace(/\.list$/i, '').replace(/[\\/]/g, '_')
  return toPascalCase(`${prefix}_${key}`)
}

/**
 * Map a URL in an .ini ruleset= line to a local file path under Clash/.
 */
function urlToLocalPath(source: string): string | null {
  if (source.startsWith('[]')) return null // inline rule
  const m = source.match(/Clash\/(.+?)\.list$/i)
  if (!m) return null
  return m[1] // e.g. "BanAD" or "Ruleset/Netflix"
}

/**
 * Build a lookup map: localPath → variableName
 */
interface RuleMapEntry {
  varName: string
  lines: string[]
}

function buildRuleMap(): Map<string, RuleMapEntry> {
  const map = new Map<string, RuleMapEntry>()

  function scan(dir: string, prefix: string) {
    if (!fs.existsSync(dir)) return
    for (const entry of fs.readdirSync(dir)) {
      const full = path.join(dir, entry)
      const stat = fs.statSync(full)
      if (stat.isFile() && entry.endsWith('.list')) {
        const rel = path.relative(CLASH_DIR, full)
        const localPath = rel.replace(/\.list$/i, '')
        const lines = readFileLines(full)
        if (lines.length > 0) {
          map.set(localPath, {
            varName: ruleVarName(rel, prefix),
            lines,
          })
        }
      }
    }
  }

  scan(CLASH_DIR, 'main')
  scan(RULESET_DIR, 'ruleset')
  return map
}

// ──────────────────────────────────────────────
// Generate rules.ts and ruleset.ts
// ──────────────────────────────────────────────

function generateRulesFile(ruleMap: Map<string, RuleMapEntry>, prefix: string, dir: string): string {
  let output = `// ⚡ Auto-generated by codegen.ts — DO NOT EDIT\n\n`
  output += `import type { RuleLine } from '../engine/types'\n\n`

  const entries = [...ruleMap.entries()]
    .filter(([localPath]) => !localPath.includes('/') && !localPath.includes('\\'))
    .sort(([a], [b]) => a.localeCompare(b))

  if (entries.length === 0) {
    output += `// No rules in ${dir}\n`
    return output
  }

  for (const [, entry] of entries) {
    output += `/** ${entry.lines.length} rules */\n`
    output += `export const ${entry.varName}: RuleLine[] = [\n`
    for (const line of entry.lines) {
      output += `  '${escapeForTemplate(line)}',\n`
    }
    output += `];\n\n`
  }

  return output
}

function generateRulesetFile(ruleMap: Map<string, RuleMapEntry>): string {
  let output = `// ⚡ Auto-generated by codegen.ts — DO NOT EDIT\n\n`
  output += `import type { RuleLine } from '../engine/types'\n\n`

  const entries = [...ruleMap.entries()]
    .filter(([localPath]) => localPath.includes('/') || localPath.includes('\\'))
    .sort(([a], [b]) => a.localeCompare(b))

  if (entries.length === 0) {
    output += `// No rules in Clash/Ruleset/\n`
    return output
  }

  for (const [, entry] of entries) {
    output += `/** ${entry.lines.length} rules */\n`
    output += `export const ${entry.varName}: RuleLine[] = [\n`
    for (const line of entry.lines) {
      output += `  '${escapeForTemplate(line)}',\n`
    }
    output += `];\n\n`
  }

  return output
}

// ──────────────────────────────────────────────
// Generate presets.ts
// ──────────────────────────────────────────────

interface ParsedRulesetEntry {
  group: string
  source: string
}

function parseIniRulesets(filePath: string): ParsedRulesetEntry[] {
  const content = fs.readFileSync(filePath, 'utf-8')
  const lines = content.split('\n').map(l => l.trim())
  const result: ParsedRulesetEntry[] = []

  for (const line of lines) {
    if (line.startsWith(';') || line.startsWith('#') || line === '') continue
    if (line.startsWith('ruleset=')) {
      const body = line.slice('ruleset='.length)
      const firstComma = body.indexOf(',')
      if (firstComma === -1) continue
      const group = body.slice(0, firstComma).trim()
      const source = body.slice(firstComma + 1).trim()
      result.push({ group, source })
    }
  }
  return result
}

/**
 * Extract Chinese description from .ini file comments.
 * Reads comments between [custom] and the first non-comment config line.
 */
function extractDescription(filePath: string): string {
  const content = fs.readFileSync(filePath, 'utf-8')
  const lines = content.split('\n').map(l => l.trim())

  const desc: string[] = []
  let inSection = false

  for (const line of lines) {
    if (line === '[custom]') {
      inSection = true
      continue
    }
    if (!inSection) continue

    // Stop at actual config lines
    if (line.startsWith('ruleset=') || line.startsWith('custom_proxy_group=') || line.startsWith('enable_')) {
      break
    }

    if (line.startsWith(';')) {
      const text = line.slice(1).trim()
      // Skip boilerplate
      if (!text || text.includes('不要随意改变关键字') || text.includes('acl4SSR规则')) continue
      if (text.startsWith('设置')) continue
      desc.push(text)
    }
  }

  return desc.join('；') || 'ACL4SSR 配置方案'
}

interface ParsedGroupLine {
  raw: string
}

function parseIniGroups(filePath: string): ParsedGroupLine[] {
  const content = fs.readFileSync(filePath, 'utf-8')
  const lines = content.split('\n').map(l => l.trim())
  const result: ParsedGroupLine[] = []

  for (const line of lines) {
    if (line.startsWith(';') || line.startsWith('#') || line === '') continue
    if (line.startsWith('custom_proxy_group=')) {
      result.push({ raw: line.slice('custom_proxy_group='.length) })
    }
  }
  return result
}

function emitGroupDef(raw: string): string {
  const parts = raw.split('`')
  if (parts.length < 2) return ''

  const name = parts[0].trim()
  const type = parts[1].trim()

  let url = ''
  let interval = 300
  let timeout = 5000
  let tolerance = 50
  const refs: string[] = []

  // Scan backward for URL
  let refEnd = parts.length
  for (let i = parts.length - 1; i > 1; i--) {
    const p = parts[i].trim()
    if (p.startsWith('http://') || p.startsWith('https://')) {
      url = p
      refEnd = i
      if (i + 1 < parts.length) {
        const params = parts[i + 1].split(',')
        interval = Number.parseInt(params[0].trim()) || 300
        if (params.length > 1 && params[1].trim()) timeout = Number.parseInt(params[1].trim()) || 5000
        if (params.length > 2 && params[2].trim()) tolerance = Number.parseInt(params[2].trim()) || 50
      }
    }
  }

  for (let i = 2; i < refEnd; i++) {
    const r = parts[i].trim()
    if (r) refs.push(r)
  }

  const refsTs = refs.map((ref) => {
    if (ref === 'DIRECT') return '{ kind: "direct" as const }'
    if (ref === 'REJECT') return '{ kind: "reject" as const }'
    if (ref === '.*') return '{ kind: "pattern" as const, pattern: ".*" }'
    if (ref.startsWith('[]')) {
      const gn = ref.slice(2)
      if (gn === 'DIRECT') return '{ kind: "direct" as const }'
      if (gn === 'REJECT') return '{ kind: "reject" as const }'
      if (gn === 'AUTO') return '{ kind: "pattern" as const, pattern: ".*" }'
      return `{ kind: "group" as const, name: "${escapeForTemplate(gn)}" }`
    }
    return `{ kind: "pattern" as const, pattern: "${escapeForTemplate(ref)}" }`
  }).join(',\n      ')

  const urlStr = url ? `"${escapeForTemplate(url)}"` : 'undefined'

  return `  {
    name: "${escapeForTemplate(name)}",
    type: "${type}" as const,
    refs: [${refsTs}],
    url: ${urlStr},
    interval: ${interval},
    tolerance: ${tolerance},
    timeout: ${timeout},
  }`
}

function generatePresetsTs(ruleMap: Map<string, RuleMapEntry>): string {
  let output = `// ⚡ Auto-generated by codegen.ts — DO NOT EDIT\n`
  output += `// Preset configurations from Clash/config/*.ini\n\n`
  output += `import type { Preset, RulesetEntry } from '../engine/types'\n\n`

  // Generate a combined import from rules and ruleset
  const allVars = new Set<string>()
  for (const [, entry] of ruleMap) {
    allVars.add(entry.varName)
  }

  if (allVars.size > 0) {
    const sortedVars = [...allVars].sort()
    output += `import {\n`
    const fromRules = sortedVars.filter(v => v.startsWith('Main'))
    const fromRuleset = sortedVars.filter(v => v.startsWith('Ruleset'))

    for (const v of fromRules) {
      output += `  ${v} as _r_${v},\n`
    }
    output += `} from './rules'\n\n`
    output += `import {\n`
    for (const v of fromRuleset) {
      output += `  ${v} as _rs_${v},\n`
    }
    output += `} from './ruleset'\n\n`

    // Build a lookup from localPath → variable name (with alias prefix)
    output += `// Rule lookup by local path\n`
    output += `const _RULES: Record<string, readonly string[]> = {\n`
    for (const [localPath, entry] of ruleMap) {
      const alias = entry.varName.startsWith('Main') ? `_r_${entry.varName}` : `_rs_${entry.varName}`
      output += `  '${escapeForTemplate(localPath)}': ${alias},\n`
    }
    output += `};\n\n`
  }

  // Parse each .ini
  const iniFiles = fs.readdirSync(CONFIG_DIR)
    .filter(f => f.endsWith('.ini'))
    .sort()

  for (const iniFile of iniFiles) {
    const baseName = iniFile.replace('.ini', '')
    const displayName = baseName.startsWith('ACL4SSR_') ? baseName.slice(8).replace(/_/g, ' ') : baseName
    const varName = toPascalCase(`preset_${baseName}`)

    const rulesets = parseIniRulesets(path.join(CONFIG_DIR, iniFile))
    const groups = parseIniGroups(path.join(CONFIG_DIR, iniFile))

    // Build ruleset entries
    const rulesetDefs: string[] = []
    for (const rs of rulesets) {
      if (rs.source.startsWith('[]')) {
        const inline = rs.source.slice(2)
        const escaped = escapeForTemplate(inline)
        rulesetDefs.push(`    { group: "${escapeForTemplate(rs.group)}", rules: ["${escaped}"], inline: true }`)
      } else {
        const localPath = urlToLocalPath(rs.source)
        if (localPath && ruleMap.has(localPath)) {
          rulesetDefs.push(`    { group: "${escapeForTemplate(rs.group)}", rules: _RULES["${escapeForTemplate(localPath)}"] as string[], inline: false }`)
        }
      }
    }

    const groupDefs = groups.map(g => emitGroupDef(g.raw)).filter(Boolean)

    const description = extractDescription(path.join(CONFIG_DIR, iniFile))

    output += `export const ${varName}: Preset = {\n`
    output += `  name: "${escapeForTemplate(displayName)}",\n`
    output += `  description: "${escapeForTemplate(description)}",\n`
    output += `  rulesets: [\n${rulesetDefs.join(',\n') || '    // no rulesets'}\n  ],\n`
    output += `  groups: [\n${groupDefs.join(',\n') || '    // no groups'}\n  ],\n`
    output += `};\n\n`
  }

  // Export ALL_PRESETS
  const presetVars = iniFiles
    .filter(f => {
      const bn = f.replace('.ini', '')
      const rulesets = parseIniRulesets(path.join(CONFIG_DIR, f))
      const groups = parseIniGroups(path.join(CONFIG_DIR, f))
      return rulesets.length > 0 || groups.length > 0
    })
    .map(f => ({
      baseName: f.replace('.ini', ''),
      varName: toPascalCase(`preset_${f.replace('.ini', '')}`),
    }))

  output += `/** All presets */\n`
  output += `export const ALL_PRESETS: Record<string, Preset> = {\n`
  for (const p of presetVars) {
    output += `  "${escapeForTemplate(p.baseName)}": ${p.varName},\n`
  }
  output += `};\n\n`

  output += `export function getPresetByName(name: string): Preset | undefined {\n`
  output += `  return ALL_PRESETS[name];\n`
  output += `}\n\n`

  output += `export function getAllPresetNames(): string[] {\n`
  output += `  return Object.keys(ALL_PRESETS);\n`
  output += `}\n`

  return output
}

// ──────────────────────────────────────────────
// Generate index.ts
// ──────────────────────────────────────────────

function generateIndexTs(): string {
  return `// ⚡ Auto-generated by codegen.ts — DO NOT EDIT
export { getPresetByName, getAllPresetNames, ALL_PRESETS } from './presets'
export * from './rules'
export * from './ruleset'
`
}

// ──────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────

function main() {
  console.log('🔨 ACL4SSR Codegen')
  console.log('  ACL4SSR root:', ACL4SSR_DIR)
  console.log('  Output dir:  ', OUTPUT_DIR)

  fs.mkdirSync(OUTPUT_DIR, { recursive: true })

  // Build complete rule map
  const ruleMap = buildRuleMap()
  const mainEntries = [...ruleMap.entries()].filter(([k]) => !k.includes('/') && !k.includes('\\'))
  const rulesetEntries = [...ruleMap.entries()].filter(([k]) => k.includes('/') || k.includes('\\'))
  console.log(`\n📋 Rules found: ${mainEntries.length} main + ${rulesetEntries.length} ruleset`)

  // Generate rules.ts
  console.log('  Writing rules.ts...')
  fs.writeFileSync(path.join(OUTPUT_DIR, 'rules.ts'), generateRulesFile(ruleMap, 'main', 'Clash/'), 'utf-8')

  // Generate ruleset.ts
  console.log('  Writing ruleset.ts...')
  fs.writeFileSync(path.join(OUTPUT_DIR, 'ruleset.ts'), generateRulesetFile(ruleMap), 'utf-8')

  // Generate presets.ts
  console.log('  Writing presets.ts...')
  fs.writeFileSync(path.join(OUTPUT_DIR, 'presets.ts'), generatePresetsTs(ruleMap), 'utf-8')

  // Generate index.ts
  console.log('  Writing index.ts...')
  fs.writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), generateIndexTs(), 'utf-8')

  console.log('\n✅ Codegen complete!')
}

main()
