/**
 * Codegen script: converts ACL4SSR rule files into TypeScript modules.
 *
 * Scans:
 *   - ../Clash/*.list          → rule arrays  → server/codegen/rules.ts
 *   - ../Clash/Ruleset/*.list  → rule arrays  → server/codegen/ruleset.ts
 *   - ../Clash/config/*.ini    → preset defs  → server/codegen/presets.ts
 *
 * Run: npx tsx scripts/codegen.ts
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

// ──────────────────────────────────────────────
// Path constants
// ──────────────────────────────────────────────

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const ACL4SSR_DIR = path.resolve(ROOT, 'ACL4SSR')
const CLASH_DIR = path.join(ACL4SSR_DIR, 'Clash')
const RULESET_DIR = path.join(CLASH_DIR, 'Ruleset')
const CONFIG_DIR = path.join(CLASH_DIR, 'config')
const OUTPUT_DIR = path.join(ROOT, 'server', 'codegen')

// ──────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────

function readLines(filePath: string): string[] {
  if (!fs.existsSync(filePath)) return []
  return fs.readFileSync(filePath, 'utf-8')
    .replace(/\r\n/g, '\n').split('\n').map(l => l.trim())
}

function readFileLines(filePath: string): string[] {
  return readLines(filePath)
    .filter(l => l !== '' && !l.startsWith('#') && !l.startsWith(';'))
}

function toPascalCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9]/g, '_')
    .replace(/(_|^)([a-z])/g, (_, __, c) => c.toUpperCase())
    .replace(/^([0-9])/, '_$1')
}

function escapeForTemplate(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/'/g, '\\\'')
    .replace(/\r/g, '')
    .replace(/\n/g, '\\n')
}

/** Generate a variable name for a rule file path relative to Clash/ */
function ruleVarName(relativePath: string, prefix: string): string {
  const key = relativePath.replace(/\.list$/i, '').replace(/[\\/]/g, '_')
  return toPascalCase(`${prefix}_${key}`)
}

/**
 * Map a URL in an .ini ruleset= line to a local file path under Clash/.
 */
function urlToLocalPath(source: string): string | null {
  if (source.startsWith('[]')) return null // inline rule
  const m = source.match(/Clash\/(.+?)\.list$/i)
  if (!m) return null
  return m[1] // e.g. "BanAD" or "Ruleset/Netflix"
}

/**
 * Build a lookup map: localPath → variableName
 */
interface RuleMapEntry {
  varName: string
  lines: string[]
}

function buildRuleMap(): Map<string, RuleMapEntry> {
  const map = new Map<string, RuleMapEntry>()

  function scan(dir: string, prefix: string) {
    if (!fs.existsSync(dir)) return
    for (const entry of fs.readdirSync(dir)) {
      const full = path.join(dir, entry)
      const stat = fs.statSync(full)
      if (stat.isFile() && entry.endsWith('.list')) {
        const rel = path.relative(CLASH_DIR, full)
        const localPath = rel.replace(/\.list$/i, '')
        const lines = readFileLines(full)
        if (lines.length > 0) {
          map.set(localPath, {
            varName: ruleVarName(rel, prefix),
            lines,
          })
        }
      }
    }
  }

  scan(CLASH_DIR, 'main')
  scan(RULESET_DIR, 'ruleset')
  return map
}

// ──────────────────────────────────────────────
// Generate rules.ts and ruleset.ts (unified)
// ──────────────────────────────────────────────

function generateRuleModule(
  ruleMap: Map<string, RuleMapEntry>,
  filter: (localPath: string) => boolean,
  emptyComment: string,
): string {
  let output = `// ⚡ Auto-generated by codegen.ts — DO NOT EDIT\n\n`
  output += `import type { RuleLine } from '../engine/types'\n\n`

  const entries = [...ruleMap.entries()]
    .filter(([localPath]) => filter(localPath))
    .sort(([a], [b]) => a.localeCompare(b))

  if (entries.length === 0) {
    output += `// No rules in ${emptyComment}\n`
    return output
  }

  for (const [, entry] of entries) {
    output += `/** ${entry.lines.length} rules */\n`
    output += `export const ${entry.varName}: RuleLine[] = [\n`
    for (const line of entry.lines) {
      output += `  '${escapeForTemplate(line)}',\n`
    }
    output += `];\n\n`
  }

  return output
}

// ──────────────────────────────────────────────
// Generate presets.ts
// ──────────────────────────────────────────────

interface ParsedRulesetEntry {
  group: string
  source: string
}

function parseIniRulesets(lines: string[]): ParsedRulesetEntry[] {
  const result: ParsedRulesetEntry[] = []
  for (const line of lines) {
    if (line.startsWith(';') || line.startsWith('#') || line === '') continue
    if (line.startsWith('ruleset=')) {
      const body = line.slice('ruleset='.length)
      const firstComma = body.indexOf(',')
      if (firstComma === -1) continue
      const group = body.slice(0, firstComma).trim()
      const source = body.slice(firstComma + 1).trim()
      result.push({ group, source })
    }
  }
  return result
}

interface ParsedGroupLine {
  raw: string
}

function parseIniGroups(lines: string[]): ParsedGroupLine[] {
  const result: ParsedGroupLine[] = []
  for (const line of lines) {
    if (line.startsWith(';') || line.startsWith('#') || line === '') continue
    if (line.startsWith('custom_proxy_group=')) {
      result.push({ raw: line.slice('custom_proxy_group='.length) })
    }
  }
  return result
}

/**
 * Extract Chinese description from .ini file comments.
 * Reads comments between [custom] and the first non-comment config line.
 */
function extractDescription(lines: string[]): string {
  const desc: string[] = []
  let inSection = false

  for (const line of lines) {
    if (line === '[custom]') {
      inSection = true
      continue
    }
    if (!inSection) continue

    // Stop at actual config lines
    if (line.startsWith('ruleset=') || line.startsWith('custom_proxy_group=') || line.startsWith('enable_')) {
      break
    }

    if (line.startsWith(';')) {
      const text = line.slice(1).trim()
      // Skip boilerplate
      if (!text || text.includes('不要随意改变关键字') || text.includes('acl4SSR规则')) continue
      if (text.startsWith('设置')) continue
      desc.push(text)
    }
  }

  return desc.join('；') || 'ACL4SSR 配置方案'
}

// ── Group parsing & code generation (split) ──

interface GroupRefDef {
  kind: 'direct' | 'reject' | 'pattern' | 'group'
  value?: string
}

interface ParsedGroup {
  name: string
  type: string
  refs: GroupRefDef[]
  url?: string
  interval: number
  timeout: number
  tolerance: number
}

function parseGroupDef(raw: string): ParsedGroup | null {
  const parts = raw.split('`')
  if (parts.length < 2) return null

  const name = parts[0].trim()
  const type = parts[1].trim()

  let url: string | undefined
  let interval = 300
  let timeout = 5000
  let tolerance = 50
  const refs: GroupRefDef[] = []

  // Scan backward for URL
  let refEnd = parts.length
  for (let i = parts.length - 1; i > 1; i--) {
    const p = parts[i].trim()
    if (p.startsWith('http://') || p.startsWith('https://')) {
      url = p
      refEnd = i
      if (i + 1 < parts.length) {
        const params = parts[i + 1].split(',')
        interval = Number.parseInt(params[0].trim()) || 300
        if (params.length > 1 && params[1].trim()) timeout = Number.parseInt(params[1].trim()) || 5000
        if (params.length > 2 && params[2].trim()) tolerance = Number.parseInt(params[2].trim()) || 50
      }
    }
  }

  for (let i = 2; i < refEnd; i++) {
    const r = parts[i].trim()
    if (!r) continue

    if (r === 'DIRECT') {
      refs.push({ kind: 'direct' })
    } else if (r === 'REJECT') {
      refs.push({ kind: 'reject' })
    } else if (r === '.*') {
      refs.push({ kind: 'pattern', value: '.*' })
    } else if (r.startsWith('[]')) {
      const gn = r.slice(2)
      if (gn === 'DIRECT') {
        refs.push({ kind: 'direct' })
      } else if (gn === 'REJECT') {
        refs.push({ kind: 'reject' })
      } else if (gn === 'AUTO') {
        refs.push({ kind: 'pattern', value: '.*' })
      } else {
        refs.push({ kind: 'group', value: gn })
      }
    } else {
      refs.push({ kind: 'pattern', value: r })
    }
  }

  return { name, type, refs, url, interval, timeout, tolerance }
}

function emitGroupTs(group: ParsedGroup): string {
  const refsTs = group.refs.map((ref) => {
    switch (ref.kind) {
      case 'direct': return '{ kind: "direct" as const }'
      case 'reject': return '{ kind: "reject" as const }'
      case 'pattern': return `{ kind: "pattern" as const, pattern: "${escapeForTemplate(ref.value!)}" }`
      case 'group': return `{ kind: "group" as const, name: "${escapeForTemplate(ref.value!)}" }`
    }
  }).join(',\n      ')

  const urlStr = group.url ? `"${escapeForTemplate(group.url)}"` : 'undefined'

  return `  {
    name: "${escapeForTemplate(group.name)}",
    type: "${group.type}" as const,
    refs: [${refsTs}],
    url: ${urlStr},
    interval: ${group.interval},
    tolerance: ${group.tolerance},
    timeout: ${group.timeout},
  }`
}

// ── Preset cache ──

interface PresetCacheEntry {
  displayName: string
  varName: string
  rulesetDefs: string[]
  groupDefs: string[]
  description: string
}

function buildPresetCache(
  ruleMap: Map<string, RuleMapEntry>,
): Map<string, PresetCacheEntry> {
  const cache = new Map<string, PresetCacheEntry>()
  const iniFiles = fs.readdirSync(CONFIG_DIR)
    .filter(f => f.endsWith('.ini'))
    .sort()

  for (const iniFile of iniFiles) {
    const baseName = iniFile.replace('.ini', '')
    const displayName = baseName.startsWith('ACL4SSR_') ? baseName.slice(8).replace(/_/g, ' ') : baseName
    const varName = toPascalCase(`preset_${baseName}`)

    const lines = readLines(path.join(CONFIG_DIR, iniFile))
    const rulesets = parseIniRulesets(lines)
    const groups = parseIniGroups(lines)
    const description = extractDescription(lines)

    // Build ruleset entries
    const rulesetDefs: string[] = []
    for (const rs of rulesets) {
      if (rs.source.startsWith('[]')) {
        const inline = rs.source.slice(2)
        const escaped = escapeForTemplate(inline)
        rulesetDefs.push(`    { group: "${escapeForTemplate(rs.group)}", rules: ["${escaped}"], inline: true }`)
      }
      else {
        const localPath = urlToLocalPath(rs.source)
        if (localPath && ruleMap.has(localPath)) {
          rulesetDefs.push(`    { group: "${escapeForTemplate(rs.group)}", rules: _RULES["${escapeForTemplate(localPath)}"] as string[], inline: false }`)
        }
      }
    }

    const groupDefs = groups
      .map(g => parseGroupDef(g.raw))
      .filter((g): g is ParsedGroup => g !== null)
      .map(g => emitGroupTs(g))

    cache.set(iniFile, { displayName, varName, rulesetDefs, groupDefs, description })
  }

  return cache
}

function emitPresetTs(ruleMap: Map<string, RuleMapEntry>, cache: Map<string, PresetCacheEntry>): string {
  let output = `// ⚡ Auto-generated by codegen.ts — DO NOT EDIT\n`
  output += `// Preset configurations from Clash/config/*.ini\n\n`
  output += `import type { Preset, RulesetEntry } from '../engine/types'\n\n`

  // Generate a combined import from rules and ruleset
  const allVars = new Set<string>()
  for (const [, entry] of ruleMap) {
    allVars.add(entry.varName)
  }

  if (allVars.size > 0) {
    const sortedVars = [...allVars].sort()
    output += `import {\n`
    const fromRules = sortedVars.filter(v => v.startsWith('Main'))
    const fromRuleset = sortedVars.filter(v => v.startsWith('Ruleset'))

    for (const v of fromRules) {
      output += `  ${v} as _r_${v},\n`
    }
    output += `} from './rules'\n\n`
    output += `import {\n`
    for (const v of fromRuleset) {
      output += `  ${v} as _rs_${v},\n`
    }
    output += `} from './ruleset'\n\n`

    // Build a lookup from localPath → variable name (with alias prefix)
    output += `// Rule lookup by local path\n`
    output += `const _RULES: Record<string, readonly string[]> = {\n`
    for (const [localPath, entry] of ruleMap) {
      const alias = entry.varName.startsWith('Main') ? `_r_${entry.varName}` : `_rs_${entry.varName}`
      output += `  '${escapeForTemplate(localPath)}': ${alias},\n`
    }
    output += `};\n\n`
  }

  // Emit each preset
  const sortedKeys = [...cache.keys()].sort()
  for (const iniFile of sortedKeys) {
    const { displayName, varName, rulesetDefs, groupDefs, description } = cache.get(iniFile)!

    output += `export const ${varName}: Preset = {\n`
    output += `  name: "${escapeForTemplate(displayName)}",\n`
    output += `  description: "${escapeForTemplate(description)}",\n`
    output += `  rulesets: [\n${rulesetDefs.join(',\n') || '    // no rulesets'}\n  ],\n`
    output += `  groups: [\n${groupDefs.join(',\n') || '    // no groups'}\n  ],\n`
    output += `};\n\n`
  }

  // Export ALL_PRESETS (only presets that have rulesets or groups)
  const presetVars = sortedKeys
    .filter(f => {
      const e = cache.get(f)!
      return e.rulesetDefs.length > 0 || e.groupDefs.length > 0
    })
    .map(f => ({
      baseName: f.replace('.ini', ''),
      varName: cache.get(f)!.varName,
    }))

  output += `/** All presets */\n`
  output += `export const ALL_PRESETS: Record<string, Preset> = {\n`
  for (const p of presetVars) {
    output += `  "${escapeForTemplate(p.baseName)}": ${p.varName},\n`
  }
  output += `};\n\n`

  output += `export function getPresetByName(name: string): Preset | undefined {\n`
  output += `  return ALL_PRESETS[name];\n`
  output += `}\n\n`

  output += `export function getAllPresetNames(): string[] {\n`
  output += `  return Object.keys(ALL_PRESETS);\n`
  output += `}\n`

  return output
}

// ──────────────────────────────────────────────
// Generate index.ts
// ──────────────────────────────────────────────

function generateIndexTs(): string {
  return `// ⚡ Auto-generated by codegen.ts — DO NOT EDIT
export { getPresetByName, getAllPresetNames, ALL_PRESETS } from './presets'
export * from './rules'
export * from './ruleset'
`
}

// ──────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────

function main() {
  console.log('🔨 ACL4SSR Codegen')
  console.log('  ACL4SSR root:', ACL4SSR_DIR)
  console.log('  Output dir:  ', OUTPUT_DIR)

  fs.mkdirSync(OUTPUT_DIR, { recursive: true })

  // Build complete rule map
  const ruleMap = buildRuleMap()
  const mainEntries = [...ruleMap.entries()].filter(([k]) => !k.includes('/') && !k.includes('\\'))
  const rulesetEntries = [...ruleMap.entries()].filter(([k]) => k.includes('/') || k.includes('\\'))
  console.log(`\n📋 Rules found: ${mainEntries.length} main + ${rulesetEntries.length} ruleset`)

  // Generate rules.ts
  console.log('  Writing rules.ts...')
  fs.writeFileSync(path.join(OUTPUT_DIR, 'rules.ts'), generateRuleModule(ruleMap, lp => !lp.includes('/') && !lp.includes('\\'), 'Clash/'), 'utf-8')

  // Generate ruleset.ts
  console.log('  Writing ruleset.ts...')
  fs.writeFileSync(path.join(OUTPUT_DIR, 'ruleset.ts'), generateRuleModule(ruleMap, lp => lp.includes('/') || lp.includes('\\'), 'Clash/Ruleset/'), 'utf-8')

  // Generate presets.ts
  console.log('  Writing presets.ts...')
  const presetCache = buildPresetCache(ruleMap)
  fs.writeFileSync(path.join(OUTPUT_DIR, 'presets.ts'), emitPresetTs(ruleMap, presetCache), 'utf-8')

  // Generate index.ts
  console.log('  Writing index.ts...')
  fs.writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), generateIndexTs(), 'utf-8')

  console.log('\n✅ Codegen complete!')
}

main()
